
version: '3'

services:
  mongo:
    image: mongo:6
    container_name: midterm-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

  web:
    image: nam8286/midterm-web:latest
    container_name: midterm-web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/products_db
      PORT: '3000'

volumes:
  mongo-data:
  uploads:
